### ISSUE TITLE
App freezes on launch

### ISSUE THREAD

**Issue by joyas11** [HenryQuan/TSFakeTouch#1]
when i installed this tweak it freezed the smashhit on launch, the app doesnt open at all it freezes (ios 16.0 dopamine 2 rootless)

**Comment by HenryQuan** [comment]
I am not sure if rootless affects anything. This was never tested on iOS 16 because it wasn't released yet.

**Comment by joyas11** [comment]
can u please help me, i wanted to create a tweak out of this which simulates only three basic touch when an app is launched but for this when testing the tweak it causing freeze on app launch. can u give me a basic one for testing if it works ill add my touch's coordinates.

**Comment by HenryQuan** [comment]
You may need some debugging. I also have no idea why it freezes, but I may have some guesses. Just add more logs under %ctor to see which one blocks the app.
> NSLog(@"FakeTouch: some log here");

It can be the timer or the dispatch queue. There are only a few lines there, just try adding more logs or commenting out some codes to see what freezes the app. You can start from almost nothing to keep figuring out exactly which line causes the issue. This was only tested on iOS 13 or 14, definitely not 16.

**Comment by joyas11** [comment]
screenSize = [[UIScreen mainScreen] bounds].size; 

this is causing issues i commented this out and tested the tweak in smashhit it worked but only on the left side 
is there an updated line for this, im a newbie learning theos :)

**Comment by joyas11** [comment]
#import "Source/PTFakeTouch.h"
#import <Foundation/Foundation.h>
#import "UIKit/UIKit.h"
#include <stdlib.h>

static NSTimer *timer;
static CGSize screenSize;

void initializeScreenSize() {
    screenSize = [UIScreen mainScreen].bounds.size;
    NSLog(@"FakeTouch: Screen size initialized.");
}

%ctor {
    // Log initialization
    NSString *logFilePath = @"/var/mobile/FakeTouch.log";
    freopen([logFilePath cStringUsingEncoding:NSASCIIStringEncoding], "a+", stderr);
    NSLog(@"FakeTouch: Log file initialized at %@", logFilePath);

    // Delay initialization of screen size
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        initializeScreenSize();
    });

    timer = [NSTimer timerWithTimeInterval:0.1 repeats:YES block:^(NSTimer *timer) {
        if (CGSizeEqualToSize(screenSize, CGSizeZero)) {
            // Screen size not initialized yet, wait for next iteration
            return;
        }
        NSLog(@"FakeTouch: Timer block started.");
        for (int i = 0; i < 3; i++) {
            CGPoint point = CGPointMake(arc4random_uniform(screenSize.width), arc4random_uniform(screenSize.height));
            NSInteger pointId = [PTFakeMetaTouch fakeTouchId:[PTFakeMetaTouch getAvailablePointId] AtPoint:point withTouchPhase:UITouchPhaseBegan];
            [PTFakeMetaTouch fakeTouchId:pointId AtPoint:point withTouchPhase:UITouchPhaseEnded];
            NSLog(@"FakeTouch: touch %d", i + 1);
        }
        NSLog(@"FakeTouch: Timer block finished.");
    }];
    [timer fire];

    NSLog(@"FakeTouch: Timer fired.");

    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 10 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
        NSLog(@"FakeTouch: 10s delay block executed.");
    });

    NSLog(@"FakeTouch: Timer added to run loop.");
    [[NSRunLoop mainRunLoop] addTimer:timer forMode:NSDefaultRunLoopMode];
}
this worked thanks man!

**Comment by HenryQuan** [comment]
Super nice, I am glad that it worked for you. I guess iOS 16 maye have done something differently compared to previous versions.

**Comment by joyas11** [comment]
how do i get touch events points to include in the code, as i said i am a beginner help would be appreciated 
all i want is to get the coordinates of the touch event, it basically clicks three times on a coordinate but idk how i am supposed to get those, im dumb :9

**Comment by HenryQuan** [comment]
It can be challenging depending on whether you want this to work on all devices or only a specific device. For a specific device, you can take a screenshot and find the position for the location. However, you need to consider the device scale so 1920 x 1080 becomes smaller like 640 x 360 (for a 3x scale). I think this will get your coordinates. If you want it to work on all devices, you may need something to locate those pixels which I don't know how to do, it is possible with something like OpenCV.

**Comment by joyas11** [comment]
i want it for my device only, is there not any app or tweak to get the (x,y) values, i searched online and this doesnt look easy atleast for me lol

**Comment by HenryQuan** [comment]
You can try https://github.com/FLEXTool/FLEX or FLEX List if it uses native UI. Otherwise, you can just count the pixel yourself as I mentioned above. You can also guess the location based on the value from `screenSize = [UIScreen mainScreen].bounds.size`. Top Left will be [0, 0] and it goes to the size you obtain from screenSize.

**Comment by joyas11** [comment]
i did it by creating my own tweak which detect coordinates where we touch 
thank you for your help bro, couldnt have done it without you :)
